color_range_list:
  ? ''
  : max:
    - 255
    - 157
    - 194
    min:
    - 78
    - 110
    - 146
  black:
    max:
    - 45
    - 150
    - 150
    min:
    - 0
    - 100
    - 100
  blue:
    max:
    - 176
    - 126
    - 118
    min:
    - 58
    - 88
    - 0
  food_waste:
    max:
    - 255
    - 103
    - 195
    min:
    - 86
    - 11
    - 15
  green:
    max:
    - 255
    - 103
    - 195
    min:
    - 86
    - 11
    - 15
  hazardous_waste:
    max:
    - 209
    - 212
    - 182
    min:
    - 119
    - 139
    - 121
  max:
  - 176
  - 126
  - 118
  min:
  - 58
  - 88
  - 0
  recyclable:
    max:
    - 113
    - 166
    - 116
    min:
    - 23
    - 119
    - 70
  recyclable_waste:
    max:
    - 180
    - 233
    - 114
    min:
    - 31
    - 91
    - 48
  red:
    max:
    - 242
    - 255
    - 255
    min:
    - 76
    - 157
    - 98
  residual_waste:
    max:
    - 255
    - 157
    - 194
    min:
    - 78
    - 110
    - 146
  tennis:
    max:
    - 255
    - 116
    - 181
    min:
    - 19
    - 79
    - 140
  white:
    max:
    - 255
    - 155
    - 155
    min:
    - 110
    - 100
    - 100
  yellow:
    max:
    - 255
    - 177
    - 184
    min:
    - 195
    - 110
    - 146
